routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/threads', 'ThreadsController@index');
Route::get('/threads/create', 'ThreadsController@create');
Route::post('/threads', 'ThreadsController@store');
Route::get('/threads/{channel}', 'ThreadsController@index');
Route::get('threads/{channel}/{thread}', 'ThreadsController@show');

Route::post('threads/{channel}/{thread}/reply', 'RepliesController@store')->name('reply.add');

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    public $timestamps = false;
    protected $fillable = ['name', 'slug'];

    public function threads(){
    	return $this->hasMany(Thread::class);
    }

    public function getRouteKeyName(){
    	return 'slug';
    }
}

app/Reply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
	protected $fillable = ['user_id','thread_id', 'body'];
	
	public function owner()
	{
		return $this->belongsTo(User::class, 'user_id');
	}
}

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
	protected $fillable = ['user_id','channel_id', 'title', 'body'];

	protected static function boot()
	{
		Parent::boot();
		static::addGlobalScope('replyCount', function($builder){
			$builder->withCount('replies');
		});
	}

	public function path()
	{
		return "/threads/{$this->channel->slug}/{$this->id}";
	}

	public function replies()
	{
		return $this->hasMany(Reply::class);
	}

	public function creator()
	{
		return $this->belongsTo(User::class, 'user_id');
	}

	public function channel(){
		return $this->belongsTo(Channel::class);
	}    

	public function addReply($reply)
	{
		return $this->replies()->create($reply);
	}


	public function scopeFilter($query, $filters){
		return $filters->apply($query);
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/RepliesController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use App\Channel;
use Illuminate\Http\Request;

class RepliesController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Channel $channel, Thread $thread)
    {
        $this->validate(request(), ['body' => 'required']);
        $thread->addReply([
                'user_id' => auth()->id(),
                'body' => request('body')
            ]);        
        return redirect($thread->path());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Thread;
use App\Channel;
use App\Filters\ThreadFilter;
use Illuminate\Http\Request;

class ThreadsController extends Controller
{
    public function __construct(){
        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Channel $channel, ThreadFilter $filters)
    {
        $threads = $this->getThreads($channel, $filters);
        if(request()->wantsJson()){
            return $threads;
        }
        //return $threads;
        return view('threads.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'title' => 'required', 
            'body' => 'required', 
            'channel_id' => 'required|exists:channels,id'
        ]);

        $thread = Thread::create([
            'user_id' => auth()->id(),
            'channel_id' => request('channel_id'),
            'title' => request('title'),
            'body' => request('body')
        ]);
        return redirect($thread->path());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Channel $channel, Thread $thread)
    {
        $replies = $thread->replies()->paginate(25);
        return view('threads.show', compact('thread', 'replies'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }



    protected function getThreads($channel, $filters){

        $threads = Thread::filter($filters);

        if($channel->exists){
            $threads->where(['channel_id' => $channel->id]);
        }

        return $threads->latest()->get();
    }


}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    Browse <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">                                        
                                        <li><a href="/threads">All Threads</a></li>
                                        <li><a href="/threads/?popular=1">Popular Threads</a></li>

                                    @if(auth()->check())
                                        <li><a href="/threads?by={{auth()->user()->name}}">My Threads</a></li>
                                    @endif
                                </ul>
                            </li>
                        <li><a href="/threads/create">New Thread</a></li>
                        <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    Channels <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                        @foreach($channels as $channel)
                                    <li>
                                        <a href="/threads/{{ $channel->slug }}/">{{ $channel->name }}</a>
                                    </li>
                                    @endforeach
                                </ul>
                            </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/shared/errors.blade.php
<div class="col-xs-12">
	@if($errors->any())
	<div class="alert alert-danger">
		@foreach($errors->all() as $error)
		<li>{{ $error }}</li>
		@endforeach			
	</div>
	@endif
	
</div>

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Create A New Thread</h4>
            </div>
                <div class="panel-body">
                <form method="post" class="form-horizontal" action="/threads">
                    {{ csrf_field() }}
                     <div class="form-group">
                         <label for="channel_id" class="col-sm-4">Channel:</label>
                         <div class="col-sm-8">
                            <select name="channel_id" id="channel_id" class="form-control">
                                <option value="">Choose A Channel</option>
                                @foreach($channels as $channel)
                                <option 
                                        value="{{ $channel->id }}" 
                                        {{ old('channel_id') == $channel->id ? 'selected' : ''}}
                                >
                                    {{ $channel->name }}
                                </option>
                                @endforeach
                            </select>
                         </div>                   
                     </div>

                     <div class="form-group">
                         <label for="title" class="col-sm-4">Title:</label>
                         <div class="col-sm-8">
                             <input type="text" value="{{ old('title') }}" name="title" class="form-control">
                         </div>                   
                     </div>
                     <div class="form-group">
                         <label for="title" class="col-sm-4">Description:</label>
                         <div class="col-sm-8">
                             <textarea name="body" class="form-control">{{ old('body') }}</textarea>
                         </div>                   
                     </div>

                     <div class="form-group">
                      <div class="col-sm-offset-4 col-sm-8">
                         <input type="submit" value="Publish" class="btn btn-primary">
                     </div>                   
                 </div>

                 @include('shared.errors')

             </form>


         </div>

     </div>
 </div>
</div>
</div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @foreach($threads as $thread)
            <div class="panel panel-default">
                <div class="panel-heading"><a href="{{ $thread->path() }}"> {{ $thread->title }}</a></div>

                <div class="panel-body">
                    {{ $thread->body }}
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/threads/reply.blade.php
<div class="panel panel-default">

	<div class="panel-heading">
		<h4 class="panel-title">
			<a href="#">{{ $reply->owner->name }}</a> said .. {{ $reply->created_at->diffForHumans() }}
		</h4>
	</div>

	<div class="panel-body">
		{{ $reply->body }}
	</div>
</div>

resources/views/threads/reply_form.blade.php
<form class="form-horizontal" method="post" action="{{$thread->path()}}/reply">
	<div class="col-xs-12 form-group">
		{{ csrf_field() }}
		<textarea name="body" class="form-control" placeholder="Has something to say.."></textarea>
	</div>
	<div class="col-xs-12 form-group">
		<input type="submit" class="btn btn-primary" value="Reply"></textarea>
	</div>

	@include('shared.errors')

</form>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $thread->title }}</div>

                <div class="panel-body">
                    {{ $thread->body }}
                </div>
            </div>


            <!-- foreach block for reply -->
                {{-- $thread->replies --}}
                
                @foreach($replies as $reply)
                    @include('threads.reply')
                @endforeach

                {{ $replies->links() }}

                <div class="clearfix"></div>

            @if(auth()->check())
                @include('threads.reply_form')
            @else
            <p>Please <a href="{{ route('login') }}">sign in</a> to participate on this thread </p>    
            @endif
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">Meta Info</div>

                <div class="panel-body">
                    This thread was published {{ $thread->created_at->diffForHumans() }} by <a href="#">{{ $thread->creator->name }}</a> and currently has {{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection